spark:
    job_name: "staging-xwj-KernelEngine"
    master: "k8s://192.168.1.63:6443"
    conf: "spark.driver.memory=6g;
           spark.executor.memory=6g;
           spark.executor.instances=5;
           spark.memory.offHeap.enabled=true;
           spark.memory.offHeap.size=4g;
           spark.eventLog.dir=/mnt/fuse_cephfs/data/spark/eventLog;
           spark.eventLog.enabled=true"
#spark.sql.session.timeZone=CST
minio:
    endpoint:   "http://10.57.232.167:31359"
    accessKey:  "AKIAIOSFODNN7EXAMPLE"
    secretKey:  "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    bucket:     "rca-staging"

cockroachdb:
    adapter:    "postgresql"
    host:       "10.57.232.61"
    port:       "26257"
    sslmode:    "require"
    database:   "rca-ipbd-lx-printer"
    username:   "bigdata"
    password:   "bigdata"
    conn_str:   "jdbc:{{adapter}}://{{host}}:{{port}}/{{database}}"

mariadb:
    adapter:    "mysql"
    host:       "10.57.232.61"
    port:       "3308"
    database:   "rca-staging-ipbd-lx-printer"
    username:   "edgeserver"
    password:   "Foxconn123654!@"
    conn_str:   "jdbc:{{adapter}}://{{host}}:{{port}}/{{database}}?useSSL=false&useUnicode=true&characterEncoding=UTF-8"

general:
    factory: "CQ"
    from_minio: "true"

part_vendor_rules:
    CD: "PARTSN,1,2"
    CAL: "PARTSN,1,3"
    LK: "PARTSN,9,10"
    C44: "PARTSN,1,3"
    4BH6: "PARTSN,1,4"

part_datecode_rules:
    CD: "PARTSN,3,6"
    CAL: "PARTSN,4,6"
    LK: "PARTSN,2,5"
    C44: "PARTSN,4,6"
    4BH6: "PARTSN,10,14"

local_log_path:
    data_base_path: "file:/C:/Users/foxconn/Desktop/RCA/ask/.txt"
    wip_path: "{{data_base_path}}/IPPD-L10_SFC_20190313.txt"
    wip_parts_path: "{{data_base_path}}/IPPD-L10_PARTS_20190313.txt"
    bobcat_path: "{{data_base_path}}/IPPD-L10_TEST_20190313.txt"
    wip_file_limits: "30"
    wip_parts_file_limits: "30"
    bobcat_file_limits: "0"

    test_detail_compression_path: "{{data_base_path}}/TEST_DETAIL_COMPRESSION/vfpa_trans_fail_list_20190513-20190520.tar.xz"
    test_detail_compression_tmp_path: "{{data_base_path}}/TEST_DETAIL_COMPRESSION_TMP/"
    test_detail_compression_output_path: "{{data_base_path}}/TEST_DETAIL_COMPRESSION_OUTPUT/"
    test_detail_compression_output_successful_path: "{{test_detail_compression_output_path}}/SUCCESSFUL/"
    test_detail_compression_output_failed_path: "{{test_detail_compression_output_path}}/FAILED/"
    #temp for validation
    test_detail_compression_output_result_path: "{{test_detail_compression_output_path}}/RESULT/"

    test_detail_path: "{{data_base_path}}/RCA/ask/.txt"
    test_detail_file_limits: "1"

    wo_path: "{{data_base_path}}/WO/"
    wo_file_limits: "1"

    mat_path: "{{data_base_path}}/MAT/"
    mat_file_limits: "1"

minio_log_path:
    data_base_path: "s3a://rca-staging/IPPD-L10/Data"
    wip_path: "{{data_base_path}}/SFC/R_WIP_SFC/"
    wip_parts_path: "{{data_base_path}}/SFC/R_WIP_PARTS_SFC/"
    bobcat_path: "{{data_base_path}}/Bobcat/"
    wip_file_limits: "1"
    wip_parts_file_limits: "1"
    bobcat_file_limits: "1"

    test_detail_compression_path: "{{data_base_path}}/TEST_DETAIL_COMPRESSION/"
    test_detail_compression_tmp_path: "{{data_base_path}}/TEST_DETAIL_COMPRESSION_TMP/"
    test_detail_compression_output_path: "{{data_base_path}}/TEST_DETAIL_COMPRESSION_OUTPUT/"
    test_detail_compression_output_successful_path: "{{test_detail_compression_output_path}}/SUCCESSFUL/"
    test_detail_compression_output_failed_path: "{{test_detail_compression_output_path}}/FAILED/"
    #temp for validation
    test_detail_compression_output_result_path: "{{test_detail_compression_output_path}}/RESULT/"

    test_detail_path: "{{data_base_path}}/TEST_DETAIL/"
    test_detail_file_limits: "1"

    wo_path: "{{data_base_path}}/WO/"
    wo_file_limits: "1"

    mat_path: "{{data_base_path}}/MAT/"
    mat_file_limits: "1"

summary_log_path:
    data_base_path: "s3a://rca-dev/IPPD-L10/Summary"
    tag: "KE"
    file_extension: "log"
    job_fmt: "yyyy-MM-dd HH:mm:ss"

log_prop:
    #CN8BJ7C2G1_||_CN8BJ7C2G1_||_296200140_||_V1N03B#629_||_V1N03B#629_||_Main   B_||_2018-11-19 13:39:07.467_||__||__||_TaiJi   Base_||_D626
    wip_col: "id,sn,wo,hh_part,cust_part,assembline,scantime,na1,na2,product,floor"
    wip_table: "part_master"
    wip_dt_fmt: "yyyy-MM-dd HH:mm:ss"

    #CN8BJ7C2G1_||_C189220M8PFAC_||_2018-11-19 13:39:07.467_||_F1034891_||_Main B_||_LK_||_F5S43-60001_||_F5S43-60001_||_D626_||_0
    wip_parts_col: "id,partsn,scantime,opid,assembly_station,part,hh_pard,cust_part,line,disassembly"
    wip_parts_table: "part_detail"
    wip_parts_dt_fmt: "yyyy-MM-dd HH:mm:ss"

    #CN8BS7C334_||_TLEOL_||_TLEOL_||_LC_TLEOL_41_||_11/29/2018 8:33:10 AM_||_11/29/2018 8:38:46 AM_||_0_||__||__||_11/29/2018 8:38:46 AM
    bobcat_col: "sn,station,stationcode,machine,start_time,end_time,istestfail,symptom,desc_,uploadtime,c1,c2,c3"
    bobcat_table: "test"
    bobcat_dt_fmt: "yyyy-MM-dd HH:mm:ss"

    #CN96E8B2HW06MD_||_SOR_||_SOR_||_CN96E8B2HW06MD_||_LB_TLEOL_02_||_exception_||_2019-06-14 02:18:53_||_2019-06-14 02:18:53_||_ProcVerifyComm_Wudang_||_Error: Not an object reference.&amp;#xA;in ProcVerifyComm_Wudang step._||_MP_||_null_||_CQ_||_D62_||_3_||_ProcPCClockSyncResultInfoProcVerifyComm_WudangResultInfo_||_ProcPCClockSyncResultInfoProcVerifyComm_WudangResultInfo_||_ProcPCClockSyncResultInfoProcVerifyComm_WudangResultInfo_||_ProcPCClockSyncResultInfoProcVerifyComm_WudangResultInfo_||_ProcPCClockSyncResultInfoProcVerifyComm_WudangResultInfo_||_ProcPCClockSyncResultInfopassProcVerifyComm_WudangResultInfoexception_||_ProcPCClockSyncResultInfoProcVerifyComm_WudangResultInfoError: Not an object reference.&amp;#xA;in ProcVerifyComm_Wudang step._||_2019-06-14 02:18:53_||_2019-06-14 02:18:53_||_TLEOL_||_2019-06-14 02:18:53_||_TaiJi Base_||_42.3.8 REV_37_Taiji28
    #    test_detail_col: "sn,build_name,build_description,unit_number,station_id,test_status,test_starttime,test_endtime,list_of_failure,list_of_failure_detail,test_phase,machine_id,factory_code,floor,line_id,test_item,test_value,test_unit,test_lower,test_upper,create_time,update_time,station_name,start_date,product,test_version"
    test_detail_col: "sn,build_name,build_description,unit_number,station_id,test_status,test_starttime,test_endtime,list_of_failure,list_of_failure_detail,test_phase,machine_id,factory_code,floor,line_id,test_item,test_value,test_unit,test_lower,test_upper,test_item_result,test_item_result_detail,create_time,update_time,station_name,start_date,product,test_version"
    test_detail_table: "test_detail"
    test_detail_dt_fmt: "yyyy-MM-dd HH:mm:ss"

    #CHEB_||_296269793_||_CEB1_||_V1N01B#629_||_V1N01B#629_||_V1N01B#629_||_1_||_CHEB_WO_20190524171446.dat_||_SOR_||_ZFRT_||__||_HP DeskJet 2620 All-in-One Printer_||_20190523_||_P2_||_20190523
    #SELECT product, build_name, file_name, wo, wo_type, plant_code, vendor_pn, hhpn, plan_qty, config, component_type, main_wo, upsert_time
    wo_col: "plant_code,wo,wo_type,hhpn,vendor_pn,config,plan_qty,file_name,build_name,component_type,main_wo,product,release_date,prodversion,create_date"
    wo_table: "work_order"
    wo_dt_fmt: "yyyyMMdd"

    #Taiji Base_||_SOR_||__||_V1N01B#629_||_ZFRT_||_ZFRT_||__||_V1N01B#629_||_V1N01B#629_||__||_CHEB_WO_20190524171446.dat_||__||__||__||__||__||__||__||__||__||__||_1_||_
    mat_col: "product,build_name,file_name,config_name,component_type,component,version,hhpn,oempn,description,config,vendor,per,aoh,color,config_description,oem_notes,drp_notes,notes,etas,etds,input_qty,excel_row_id"
    mat_table: "config_component"
    mat_dt_fmt: "yyyy-MM-dd HH:mm:ss"

    log_seperator: "_\\|\\|_"
    log_seperator_non_escape: "_||_"

analysis:
    fail_condition: "2"

test_floor_line:
    code_5: "D713"
    code_D714: "D714"
    code_T: "D721"
    code_4: "D722"
    code_6: "D723"
    code_F: "D621"
    code_7: "D622"
    code_B: "D623"
    code_9: "D624"
    code_8: "D625"
    code_C: "D626"
    code_G: "D631"
    code_H: "D632"
    code_Q: "D633"
    code_N: "D634"
    code_P: "D635"
    code_D: "D636"

taiji_base:
    code: "06MD,06PK,06PN,06P4,06PP,06PS,06PT,06PV,06PX,06PY,06PZ,06Q2,06Q3,06Q4,06Q7,06Q8,06Q9,06QD,070W,070X"

dataset:
    sdf_format: "M/dd/yyyy,dd.M.yyyy,M/dd/yyyy hh:mm:ss a,dd.M.yyyy hh:mm:ss a,dd.MMM.yyyy,dd-MMM-yyyy"
