spark:
    job_name: "prod-xwj-KernelEngine"
#    master: "local"
#    conf: "spark.driver.memory=2g;
#           spark.executor.memory=2g;"
    master: "k8s://192.168.1.63:6443"
    conf: "spark.memory.offHeap.enabled=false;"
minio:
    endpoint:   "http://10.57.232.167:31359"
    accessKey:  "AKIAIOSFODNN7EXAMPLE"
    secretKey:  "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    connectionSslEnabled: "false"
    bucket:     "rca-staging"

cockroachdb:
    adapter:    "postgresql"
    host1:       "10.57.232.61"
    host2:       "10.57.232.62"
    host3:       "10.57.232.63"
    port:       "26257"
    sslmode:    "require"
    database:   "rca-cartridge-nesta"
    username:   "bigdata"
    password:   "bigdata"
    #conn_str:   "jdbc:{{adapter}}://{{host}}:{{port}}/{{database}}"
    conn_str:   "jdbc:{{adapter}}://{{host1}}:{{port}},{{host2}}:{{port}},{{host3}}:{{port}}/{{database}}"

mariadb:
    adapter:    "mysql"
    loadbalance: "loadbalance"
    host:       "10.57.232.61"
    port:       "3308"
    database:   "rca-cartridge-nesta"
    username:   "edgeserver"
    password:   "Foxconn123654!@"
#    conn_str:   "jdbc:{{adapter}}://{{host}}:{{port}}/{{database}}?useSSL=false&serverTimezone=Asia/Taipei&useUnicode=true&characterEncoding=UTF-8"
    conn_str:    "jdbc:{{adapter}}:{{loadbalance}}://{{host}}:{{port}}/{{database}}?useSSL=false&serverTimezone=Asia/Taipei&useUnicode=true&characterEncoding=UTF-8"
    product_item_spec_table: "product_item_spec"
    product_station_table: "product_station"
    mat_table: "config_component"
    bigtable_datatype_table: "data_set_bigtable_columns"

general:
    factory: "CQ"
    from_minio: "true"
    env: "prod"

part_vendor_rules:
    CD: "PARTSN,1,2"
    CAL: "PARTSN,1,3"
    LK: "PARTSN,9,10"
    C44: "PARTSN,1,3"
    4BH6: "PARTSN,1,4"

part_datecode_rules:
    CD: "PARTSN,3,6"
    CAL: "PARTSN,4,6"
    LK: "PARTSN,2,5"
    C44: "PARTSN,4,6"
    4BH6: "PARTSN,10,14"

local_log_path:
    data_base_path: "file:/C:/Users/foxconn/Desktop/RCA/ask/.txt"
    wip_path: "{{data_base_path}}/IPPD-L10_SFC_20190313.txt"
    wip_parts_path: "{{data_base_path}}/IPPD-L10_PARTS_20190313.txt"
    bobcat_path: "{{data_base_path}}/IPPD-L10_TEST_20190313.txt"
    wip_file_limits: "30"
    wip_parts_file_limits: "30"
    bobcat_file_limits: "0"

    test_detail_path: "{{data_base_path}}/RCA/ask/.txt"
    test_detail_file_limits: "1"

    wo_path: "{{data_base_path}}/WO/"
    wo_file_limits: "1"

    mat_path: "{{data_base_path}}/MAT/"
    mat_file_limits: "1"

minio_log_path:
    data_base_path: "s3a://rca-ftp/Cartridge-Nesta/Data"
    wip_path: "{{data_base_path}}/SFC/R_WIP_SFC/"
    wip_parts_path: "{{data_base_path}}/SFC/R_WIP_PARTS_SFC/"
    bobcat_path: "{{data_base_path}}/Bobcat/"
    wip_file_limits: "1"
    wip_parts_file_limits: "1"
    bobcat_file_limits: "1"

    test_detail_path: "{{data_base_path}}/TEST_DETAIL/"
    test_detail_file_limits: "1"

    wo_path: "{{data_base_path}}/WO/"
    wo_file_limits: "1"

    mat_path: "{{data_base_path}}/MAT/"
    mat_file_limits: "1"

summary_log_path:
    data_base_path: "s3a://rca-ftp/Cartridge-Nesta/Summary"
    tag: "XWJ_KE"
    file_extension: "log"
    job_fmt: "yyyy-MM-dd HH:mm:ss"
    bu_name: "rca-cartridge-nesta"

log_prop:
    #CN8BJ7C2G1_||_CN8BJ7C2G1_||_296200140_||_V1N03B#629_||_V1N03B#629_||_Main   B_||_2018-11-19 13:39:07.467_||__||__||_TaiJi   Base_||_D626
    wip_col: "id,sn,wo,hh_part,cust_part,assembline,scantime,na1,na2,product,floor"
    wip_table: "part_master"
    wip_dt_fmt: "yyyy-MM-dd HH:mm:ss"
    wip_filter_col: "id,floor,wo,scantime,sn"

    #CN8BJ7C2G1_||_C189220M8PFAC_||_2018-11-19 13:39:07.467_||_F1034891_||_Main B_||_LK_||_F5S43-60001_||_F5S43-60001_||_D626_||_0
    wip_parts_col: "id,partsn,scantime,opid,assembly_station,part,hh_pard,cust_part,line,disassembly"
    wip_parts_table: "part_detail"
    wip_parts_dt_fmt: "yyyy-MM-dd HH:mm:ss"
    wip_parts_line_col: "id,scantime,line"

    #CN8BS7C334_||_TLEOL_||_TLEOL_||_LC_TLEOL_41_||_11/29/2018 8:33:10 AM_||_11/29/2018 8:38:46 AM_||_0_||__||__||_11/29/2018 8:38:46 AM
    bobcat_col: "sn,station,stationcode,machine,start_time,end_time,istestfail,symptom,desc_,uploadtime,c1,c2,c3"
    bobcat_table: "test"
    bobcat_dt_fmt: "yyyy-MM-dd HH:mm:ss"

    #CN96E8B2HW06MD_||_SOR_||_SOR_||_CN96E8B2HW06MD_||_LB_TLEOL_02_||_exception_||_2019-06-14 02:18:53_||_2019-06-14 02:18:53_||_ProcVerifyComm_Wudang_||_Error: Not an object reference.&amp;#xA;in ProcVerifyComm_Wudang step._||_MP_||_null_||_CQ_||_D62_||_3_||_ProcPCClockSyncResultInfoProcVerifyComm_WudangResultInfo_||_ProcPCClockSyncResultInfoProcVerifyComm_WudangResultInfo_||_ProcPCClockSyncResultInfoProcVerifyComm_WudangResultInfo_||_ProcPCClockSyncResultInfoProcVerifyComm_WudangResultInfo_||_ProcPCClockSyncResultInfoProcVerifyComm_WudangResultInfo_||_ProcPCClockSyncResultInfopassProcVerifyComm_WudangResultInfoexception_||_ProcPCClockSyncResultInfoProcVerifyComm_WudangResultInfoError: Not an object reference.&amp;#xA;in ProcVerifyComm_Wudang step._||_2019-06-14 02:18:53_||_2019-06-14 02:18:53_||_TLEOL_||_2019-06-14 02:18:53_||_TaiJi Base_||_42.3.8 REV_37_Taiji28
    #    test_detail_col: "sn,build_name,build_description,unit_number,station_id,test_status,test_starttime,test_endtime,list_of_failure,list_of_failure_detail,test_phase,machine_id,factory_code,floor,line_id,test_item,test_value,test_unit,test_lower,test_upper,create_time,update_time,station_name,start_date,product,test_version"
    test_detail_col: "sn,build_name,build_description,unit_number,station_id,test_status,test_starttime,test_endtime,list_of_failure,list_of_failure_detail,test_phase,machine_id,factory_code,floor,line_id,test_item,test_value,test_unit,test_lower,test_upper,test_item_result,test_item_result_detail,create_time,update_time,station_name,start_date,product,test_version"
    test_detail_table: "test_detail"
    test_detail_dt_fmt: "yyyy-MM-dd HH:mm:ss"

    #CHEB_||_296269793_||_CEB1_||_V1N01B#629_||_V1N01B#629_||_V1N01B#629_||_1_||_CHEB_WO_20190524171446.dat_||_SOR_||_ZFRT_||__||_HP DeskJet 2620 All-in-One Printer_||_20190523_||_P2_||_20190523
    #SELECT product, build_name, file_name, wo, wo_type, plant_code, vendor_pn, hhpn, plan_qty, config, component_type, main_wo, upsert_time
    wo_col: "plant_code,wo,wo_type,hhpn,vendor_pn,config,plan_qty,file_name,build_name,component_type,main_wo,product,release_date,prodversion,create_date"
    wo_table: "work_order"
    wo_dt_fmt: "yyyyMMdd"

    #Taiji Base_||_SOR_||__||_V1N01B#629_||_ZFRT_||_ZFRT_||__||_V1N01B#629_||_V1N01B#629_||__||_CHEB_WO_20190524171446.dat_||__||__||__||__||__||__||__||__||__||__||_1_||_
    mat_col: "product,build_name,file_name,config_name,component_type,component,version,hhpn,oempn,description,config,vendor,per,aoh,color,config_description,oem_notes,drp_notes,notes,etas,etds,input_qty,excel_row_id"
    mat_table: "config_component"
    mat_dt_fmt: "yyyy-MM-dd HH:mm:ss"

    log_seperator: "_\\|\\|_"
    log_seperator_non_escape: "_||_"

    mb_limits: "1"

analysis:
    fail_condition: "2"

dataset:
    sdf_format: "M/dd/yyyy,dd.M.yyyy,M/dd/yyyy hh:mm:ss a,dd.M.yyyy hh:mm:ss a,dd.MMM.yyyy,dd-MMM-yyyy"
    bigtable_datatype_col: "data_set_id,column_name,column_type,json_str"
    station_info_col: "build_description,unit_number,station_id,test_status,test_starttime,list_of_failure,test_version"
    item_info_col: "test_value,test_item_result,test_item_result_detail"
    component_info_col: "vendor,hhpn,oempn,component_type,input_qty,partsn,vendor_code,date_code"
    part_detail_col: "partsn,vendor_code,date_code,part"
    setting_col: "id,name,product,bt_name,bt_create_time,bt_last_time,bt_next_time,effective_start_date,effective_end_date,component,item,station"
    station_name_str: "station_name"
    station_info_str: "station_info"
    item_str: "item"
    item_info_str: "item_info"
    component_str: "component"
    component_info_str: "component_info"