# dev-local , dev-k8s , dtsa-lx-k8s , ipcd-lx-k8s , ipbd-lx-monitor-k8s , ipbd-lx-printer-k8s , staging-cartridge-nesta, dev-ipbd-lx-printer
mode: "dev-local"
dev-local_config_path: "conf/config_dev-local.yaml"
staging-cartridge-nesta_config_path: "conf/config_staging-cartridge-nesta.yaml"
prod-cartridge-nesta_config_path: "conf/config_prod-cartridge-nesta.yaml"
fii-cartridge-nesta_config_path: "conf/config_fii-cartridge-nesta.yaml"