# dev-local , dev-k8s , dtsa-lx-k8s , ipcd-lx-k8s , ipbd-lx-monitor-k8s , ipbd-lx-printer-k8s , cartridge-nesta-k8s, dev-ipbd-lx-printer
mode: "dev-local"
dev-local_config_path: "conf/config_dev-local.yaml"
dev-ipbd-lx-printer_config_path: "conf/config_dev-ipbd-lx-printer.yaml"
staging-ipbd-lx-printer_config_path: "conf/config_staging-ipbd-lx-printer.yaml"